# PyTorch basics on tensors!

###  

Pytorch is an amazing computational library which brings pythonic style of coding brings complex deep learning concepts right under your fingers!
Let's discuss more about the fundamental concepts and frequently used basic tensor functions that you would see very often in any github code using PyTorch!

- torch.Tensor vs torch.tensor vs torch.as_tensor()
- torch.view()
- tensor.permute()
- tensor.device()
- tensor.reshape_()
- tensor.resize()
- torch.squeeze()
- torch.unsqueeze()




In [0]:
# Import torch and other required modules
import torch

## Function 1 - torch.tensor() vs torch.Tensor() vs torch.as_tensor()



In [2]:
# Example 1 
data = [1,2,3,4]
t1 = torch.Tensor(data)
print(t1)
print(t1.dtype)           

tensor([1., 2., 3., 4.])
torch.float32


In [3]:
t2= torch.tensor(data)
print(t2)
print(t2.dtype)

tensor([1, 2, 3, 4])
torch.int64


In [4]:
import numpy as np
data2= np.array([1,2,3])
print(f'data type of data2 is - {type(data2)}')

#converting a numpy array to a tensor 
t3 = torch.as_tensor(data2)
print(f'data type of tensor t3 is - {t3.dtype}')

data type of data2 is - <class 'numpy.ndarray'>
data type of tensor t3 is - torch.int64


As you see it from the above example, the tensor 't1= torch.Tensor()' will convert the data into the default datatype-> float32, while the tensor 't2' with 'torch.tensor()' will look at the data and preserves its datatype! Also, 'tensor_astensor()' avoids creating the copy of varibles. This is because arguments to this function is passed by reference (pointers) rather than passing the values. This is very interesting implementation in software designing, known as 'The Factory function' design pattern. It is a design pattern used to define a runtime interface for creating an object. It’s called a factory because it creates various types of objects without necessarily knowing what kind of object it creates or how to create it.[1]



## Function - 2 - torch.view()




In [5]:
# Example 2
t4 = torch.rand(4, 4) #generate a matrix with rows=4 and cols=4 with randon numbers between 0 and 1 taken from uniform distribution
print(f't4 - {t4}\n')

#reshaping the tensors with new shape. This does not create a copy of t4 but works on t4 directly by passing values as reference than values.
new_t4 = t4.view(2,8)
print(f'new_tf - {new_t4}\n')


#so modifying first value in 'new_t4' must reflect in 't4'
new_t4[0][0] = 0.5
print(f't4 - {t4}')


t4 - tensor([[0.8460, 0.8770, 0.3523, 0.4718],
        [0.2623, 0.1998, 0.7822, 0.9587],
        [0.5182, 0.7398, 0.7883, 0.0823],
        [0.0253, 0.8231, 0.5043, 0.0912]])

new_tf - tensor([[0.8460, 0.8770, 0.3523, 0.4718, 0.2623, 0.1998, 0.7822, 0.9587],
        [0.5182, 0.7398, 0.7883, 0.0823, 0.0253, 0.8231, 0.5043, 0.0912]])

t4 - tensor([[0.5000, 0.8770, 0.3523, 0.4718],
        [0.2623, 0.1998, 0.7822, 0.9587],
        [0.5182, 0.7398, 0.7883, 0.0823],
        [0.0253, 0.8231, 0.5043, 0.0912]])


'View' is a very powerful implementation which is often used in computer vision to reshape the tensors! These tensors shares the same underlying data with its base tensor, meaning any modification to the new tensor made will be reflected in its parent/base tensor. This is possible due to its pass by reference implementation rather than pass by value implementation which avoids copy of data.


In [6]:
# Example 3 - breaking 
#So from the above example, the dimenality must be preserved, else it throws an error. For eg
t5 = new_t4.view(2,2)


RuntimeError: ignored

It clearly mentions that you cannot reshape a 4x4 martix into a 2x2 matrix, which can be done using slicing but not reshpaing! The correct implmentation would be.. 

In [8]:
t5 = new_t4.view(8,-1)   # in scenarios where you don't know the column/row dimensions, you can simply pass -1 to the col/row argument!
# t5 = new_t4.view(1,16)
# t5 = new_t4.view(16,1)
print(f't5 - {t5}')

t5 - tensor([[0.5000, 0.8770],
        [0.3523, 0.4718],
        [0.2623, 0.1998],
        [0.7822, 0.9587],
        [0.5182, 0.7398],
        [0.7883, 0.0823],
        [0.0253, 0.8231],
        [0.5043, 0.0912]])


## Function 3 - torch.permute()

This is related to the 'transpose' function in the python and to View in PyTorch!

In [9]:
# Example 1
data3 = torch.rand(3,2,5) #this says tha the tensor must have 2 rows and 5 columns but 2 batches(batch_first) of data
print(f'data3_shape - {data3.shape}')
print(f'data3 is - {data3}\n')


#now if we want to transpose this into a  batch_last option without any creating data copy, then
data4 = data3.permute(1,2,0)
print(f'data4_shape - {data4.shape}')
print(f'data4 - {data4}')

data3_shape - torch.Size([3, 2, 5])
data3 is - tensor([[[0.5612, 0.7003, 0.6685, 0.7845, 0.1161],
         [0.9358, 0.9018, 0.7310, 0.2631, 0.6020]],

        [[0.6280, 0.0307, 0.8031, 0.6961, 0.5546],
         [0.1915, 0.7227, 0.5936, 0.4988, 0.1031]],

        [[0.6714, 0.0198, 0.7395, 0.9165, 0.6125],
         [0.9296, 0.5828, 0.4076, 0.8963, 0.6584]]])

data4_shape - torch.Size([2, 5, 3])
data4 - tensor([[[0.5612, 0.6280, 0.6714],
         [0.7003, 0.0307, 0.0198],
         [0.6685, 0.8031, 0.7395],
         [0.7845, 0.6961, 0.9165],
         [0.1161, 0.5546, 0.6125]],

        [[0.9358, 0.1915, 0.9296],
         [0.9018, 0.7227, 0.5828],
         [0.7310, 0.5936, 0.4076],
         [0.2631, 0.4988, 0.8963],
         [0.6020, 0.1031, 0.6584]]])


This is also very oftenly used to swap the order of the tensors without creating a copy of the existing data similar to 'View' operation. Normally we come across this operaton in deep learning for vision where we would need to swap the dimensions of images as either (batch_size,W,H,channel) with (W,H,channel,batch_size) or vice-verse. A very handly function to know about.


In [10]:
# Example2
# NOTE: The permute method takes the 'indices' of the shape of the existing tensor and not some random numbers.
# If you try to access the values beyond the 'indices' 'you get dimension out of range error'

print(f'shape of data4 is - {data4.shape}\n')
for i in range(0,3):
  print(f'index {i} - {data4.shape[i]} ')
print(f'New shape of data4 after permute is - {data4.permute(0,2,3)}')

shape of data4 is - torch.Size([2, 5, 3])

index 0 - 2 
index 1 - 5 
index 2 - 3 


IndexError: ignored

It can be seen from the above exmaple that the 'permute()' function takes the indices of the shape of given tensor and swaps the rows, cols and other dimensions inline! If any value other than the indices are provided it throws an error, one such example which I often encounter is the dimension out of range error!


## Function 4 - torch.device




In [11]:
#checks if the cuda is available on your device
dev = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f'Device - {dev}')
t6 = torch.rand(4,4,dtype=torch.float64,device=dev)
print(t6)

Device - cuda
tensor([[0.4748, 0.5703, 0.5160, 0.7933],
        [0.3456, 0.4909, 0.6322, 0.7953],
        [0.3250, 0.1766, 0.7195, 0.1941],
        [0.1241, 0.1314, 0.7593, 0.5525]], device='cuda:0',
       dtype=torch.float64)


In [12]:
#you can still enforce a tensor to be on the cpu by doing the following 
t7 = torch.rand(4,4,dtype=torch.float64,device='cpu')
print(f't7 is on - {t7.device}')
if torch.cuda.is_available():
  print('Hey GPU is available, copying the tensor into GPUs memory')
  t7 = t7.cuda()
  print(f'Now t7 is on - {t7.device}')

t7 is on - cpu
Hey GPU is available, copying the tensor into GPUs memory
Now t7 is on - cuda:0


This is an amazing functionality where you can check the memory allocation of 
the tensors. Is the tensor on the CPU memory or GPU memory. By default tensors are on cpu unless specifically mentioned or copied from cpu to gpu memory.
This attribute is very frequently used doing training the deep learning models while training. If a device is GPU enabled, but for some reason you need to train models using CPU, just by sending a 'string' 

In [13]:
#the strings that must be given to the 'device' option is from a known list, any other string given will throw an error.
t8 = torch.randn(4,4,device='gpu')

RuntimeError: ignored

In [14]:
#optionally you can also do this
cuda_device = torch.device('cuda:0')
t8= torch.rand(4,4,device=cuda_device)
t8

tensor([[0.6250, 0.1002, 0.5522, 0.5335],
        [0.0229, 0.8209, 0.0298, 0.7981],
        [0.7002, 0.2035, 0.2941, 0.9794],
        [0.8305, 0.1309, 0.4619, 0.2343]], device='cuda:0')

## Function 5 - tensor.resize_()

tensor.resize_() is an interesting method which splits the parts of a tensor with certain shape and copies the data from it to form a new shape. So, the new tensor being created can have 


1.   A shape greater than the shape of the tensor being converted, and
2.   A shape smaller than the shape of the tensor being converted

In the former case, the underlying data/tensor's shape is first converted and then a new memory is filled with the resized data. But in the latter case, the underlying data/tensors are not changed but existing data is copied into a new memory!



In [26]:
data5 = torch.rand(4,4)
print(f'data5 - {data5}, shape - {data5.shape}\n')

#case: new tensor is being resized to a lesser shape
resized_data5_small = data5.resize_(3,2)
print(f'resized_data5_small - {resized_data5_small}, shape - {resized_data5_small.shape}\n')

#case: new tensor is being resized to a lesser shape
resized_data5_large = data5.resize_(5,5)
print(f'resized_data5_small - {resized_data5_large}, shape - {resized_data5_large.shape}')

data5 - tensor([[0.4278, 0.9469, 0.3868, 0.5673],
        [0.9997, 0.4777, 0.6988, 0.6179],
        [0.8054, 0.5041, 0.5840, 0.4235],
        [0.0591, 0.8856, 0.9506, 0.5793]]), shape - torch.Size([4, 4])

resized_data5_small - tensor([[0.4278, 0.9469],
        [0.3868, 0.5673],
        [0.9997, 0.4777]]), shape - torch.Size([3, 2])

resized_data5_small - tensor([[ 4.2782e-01,  9.4690e-01,  3.8676e-01,  5.6727e-01,  9.9970e-01],
        [ 4.7770e-01,  6.9882e-01,  6.1789e-01,  8.0540e-01,  5.0414e-01],
        [ 5.8399e-01,  4.2347e-01,  5.9140e-02,  8.8559e-01,  9.5057e-01],
        [ 5.7930e-01,  1.0842e-19,  1.8263e+00,  0.0000e+00,  1.7510e+00],
        [-1.0842e-19,  1.7710e+00, -0.0000e+00,  1.7117e+00,  0.0000e+00]]), shape - torch.Size([5, 5])


## Function 6 - tensor.reshape() 
- This function is very similar to the 'View' function which we saw earlier. But these can operate even on the non-contiguity tensors. 



1.   Contiguity data is when the data tensors or arrays are stored in the memory
row  wise. Please follow [this](https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch) and [this](https://stackoverflow.com/questions/26998223/what-is-the-difference-between-contiguous-and-non-contiguous-arrays/26999092#26999092) for the excellent explanations about it. So, its easy and faster to obtain the addresses of the contiguous rows if the data are stored are in contiguity fashion. 'View' function that we saw earlier imposes some contiguity constraints on the shapes of the two tensors and might break sometimes but reshape function can work with non-contiguity data also!
2.   In simpler terms, 'view' works only if tensor.is_contiguous()==True and 'reshape' works with any kind of tensors.










In [42]:
data6 = torch.rand(3,4, dtype=torch.float32)
print(f'data6 before reshaping - data6-{data6} - shape- {data6.shape}\n')

reshape_data6 = data6.reshape(2,-1)
print(f'data6 before reshaping - data6-{reshape_data6} - shape- {reshape_data6.shape}\n')


data6 before reshaping - data6-tensor([[8.3931e-01, 6.7791e-01, 2.0965e-02, 2.6047e-01],
        [3.2455e-04, 9.9850e-01, 6.6238e-01, 3.2699e-01],
        [9.8790e-01, 2.0600e-01, 3.1494e-01, 4.5801e-01]]) - shape- torch.Size([3, 4])

data6 before reshaping - data6-tensor([[8.3931e-01, 6.7791e-01, 2.0965e-02, 2.6047e-01, 3.2455e-04, 9.9850e-01],
        [6.6238e-01, 3.2699e-01, 9.8790e-01, 2.0600e-01, 3.1494e-01, 4.5801e-01]]) - shape- torch.Size([2, 6])



In [46]:
#breaking
transposed_data6 = data6.t()
print(f'transposed_data6 - {transposed_data6} and shape - {transposed_data6.shape}')
transposed_data6.view(12,-1)

transposed_data6 - tensor([[8.3931e-01, 3.2455e-04, 9.8790e-01],
        [6.7791e-01, 9.9850e-01, 2.0600e-01],
        [2.0965e-02, 6.6238e-01, 3.1494e-01],
        [2.6047e-01, 3.2699e-01, 4.5801e-01]]) and shape - torch.Size([4, 3])


RuntimeError: ignored

In [47]:
transposed_data6.reshape(12)

tensor([8.3931e-01, 3.2455e-04, 9.8790e-01, 6.7791e-01, 9.9850e-01, 2.0600e-01,
        2.0965e-02, 6.6238e-01, 3.1494e-01, 2.6047e-01, 3.2699e-01, 4.5801e-01])

# Function 7 - torch.squeeze()

Another interesting method is squeeze methof, which returns a tensor with all the dimensions of input of size 1 removed. Also, the returned tensor shares the storage with the input tensor, so changing the contents of one will change the contents of the other.


In [52]:
t = torch.ones(2,1,2,1) 
print(f't - {t}, shape - {t.shape}\n')

r = torch.squeeze(t)     # Size 2x2
print(f'r - {r}, shape- {r.shape}')

r = torch.squeeze(t, 1) 
print(f'r - {r}, shape- {r.shape}')

t - tensor([[[[1.],
          [1.]]],


        [[[1.],
          [1.]]]]), shape - torch.Size([2, 1, 2, 1])

r - tensor([[1., 1.],
        [1., 1.]]), shape- torch.Size([2, 2])
r - tensor([[[1.],
         [1.]],

        [[1.],
         [1.]]]), shape- torch.Size([2, 2, 1])


# Function 8 - torch.unsqueeze()

Just like squeeze, this unsqueeze a tensor and returns a new tensor with a dimension of size one inserted at the specified position and the returned tensor shares the same underlying data with this tensor.


In [81]:
x = torch.ones(3,4)
print(f'x- {x} and shape- {x.shape}\n')

print(f'unsqueeze - {torch.unsqueeze(x,1)}, shape -{torch.unsqueeze(x,1).shape}\n') #unsquezze at the index=1 of tensor x
print(f'unsqueeze - {torch.unsqueeze(x,0)}, shape -{torch.unsqueeze(x,0).shape}\n') #unsquezze at the index=0 of tensor x
print(f'unsqueeze - {torch.unsqueeze(x,-1)}, shape -{torch.unsqueeze(x,-1).shape}') #unsquezze at the index=2/index= -1 of tensor x


x- tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]) and shape- torch.Size([3, 4])

unsqueeze - tensor([[[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]],

        [[1., 1., 1., 1.]]]), shape -torch.Size([3, 1, 4])

unsqueeze - tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]), shape -torch.Size([1, 3, 4])

unsqueeze - tensor([[[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.]]]), shape -torch.Size([3, 4, 1])


## Conclusion

We looked into the basic operations of tensors which are very imporant in while training or developing a vision based deep learning model! We will see in further posts on how these concepts will be used to develop regression models/ classification models using PyTorch's advacned methods and concepts!

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* [1] https://medium.com/secure-and-private-ai-writing-challenge/introduction-to-tensors-2-using-pytorch-2b6270a838f
* https://stackoverflow.com/questions/49643225/whats-the-difference-between-reshape-and-view-in-pytorch
* https://stackoverflow.com/questions/26998223/what-is-the-difference-between-contiguous-and-non-contiguous-arrays/26999092#26999092


In [0]:
!pip install jovian --upgrade --quiet

In [0]:
import jovian
from nbformat import v4, write

In [0]:
# def create_empty_notebook(filename="empty.ipynb"):
#   with open(filename, 'w', encoding='utf-8') as f:
#     write(v4.new_notebook(), f, version=4)
#   return filename

In [0]:
def create_notebook(filename="colab_session.ipynb"):
  cells = []
  for session, line, (input, output) in list(get_ipython().history_manager.get_range(output=True)):
    outputs = [v4.new_output(output_type="stream", name="stdout", text=output)] if output else []
    cells.append(v4.new_code_cell(execution_count=line, source=input, outputs=outputs))

  with open(filename, 'w', encoding='utf-8') as f:
    write(v4.new_notebook(cells=cells), f, version=4)
  return filename

In [0]:
jovian.commit(project="darshansramesh/01-tensor-operations",filename=create_notebook(), environment=None, is_cli=True)